login: &login
  adapter: mysql
  username: root
  password: 
  encoding: utf8    
<% sockets = %w(/tmp/mysql.sock /var/lib/mysql/mysql.sock /var/run/mysqld/mysqld.sock /var/run/mysqld/mysqld.sock /usr/local/mysql/tmp/mysql.sock /opt/local/var/run/mysql5//mysqld.sock) %>
<% socket = sockets.detect{|socket| File.exists? socket } %>
  socket: <%= socket %>

development:
  database: bazaar_dev
  <<: *login
  
test:
  database: bazaar_test
  <<: *login